create table app_user (
    id bigint generated by default as identity primary key,
    university_id varchar(50) not null unique,
    full_name varchar(150) not null,
    email varchar(150) not null unique,
    password_hash varchar(255) not null,
    role varchar(30) not null,
    account_status varchar(30) not null,
    banned_until timestamp null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table study_resource (
    id bigint generated by default as identity primary key,
    resource_name varchar(120) not null,
    resource_type varchar(40) not null,
    zone_location varchar(80) not null,
    floor integer not null,
    status varchar(40) not null,
    has_power_outlet boolean not null default false,
    capacity integer null,
    faculty_exclusive boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table reservation (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    resource_id bigint not null,
    start_time timestamp not null,
    end_time timestamp not null,
    status varchar(40) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_reservation_user
        foreign key (user_id) references app_user(id),
    constraint fk_reservation_resource
        foreign key (resource_id) references study_resource(id)
);

create table reservation_participant (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null,
    participant_university_id varchar(50) not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_participant_reservation
        foreign key (reservation_id) references reservation(id) on delete cascade
);

create table attendance_log (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null unique,
    actual_check_in timestamp null,
    actual_check_out timestamp null,
    session_notes varchar(500) null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_attendance_reservation
        foreign key (reservation_id) references reservation(id) on delete cascade
);

create table issue_report (
    id bigint generated by default as identity primary key,
    reported_by_user_id bigint not null,
    resource_id bigint not null,
    issue_type varchar(40) not null,
    description varchar(500) not null,
    status varchar(40) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_issue_reporter
        foreign key (reported_by_user_id) references app_user(id),
    constraint fk_issue_resource
        foreign key (resource_id) references study_resource(id)
);

create index idx_reservation_user_status on reservation(user_id, status);
create index idx_reservation_resource_window on reservation(resource_id, start_time, end_time);
create index idx_resource_status on study_resource(status);
create index idx_issue_status on issue_report(status);
